### PR TITLE
Process Form 497 (Late Contributions)

### LINKED ISSUE #26: Process contributions from Form 497
The filing deadlines for Form 460 are sparse -- only two until November (9/29, 10/27) -- and between the deadlines the only data we get is from Form 497.

This form contains some sizeable contributions: $1.5M as of writing.

We will have to figure out how to deduplicate these with the Form 460 contributions after the filing deadlines, but for now we just need to include them at all.

### PR DESCRIPTION
**Pull request by tdooner**
The Late Contributions have a bunch of data that comes in between filing
deadlines (mostly about ballot measures, but also one candidate for a
school board position).

There is a gotcha in that we will have to deduplicate this later.

Fixes #26

### CODE REVIEW

**Comment by adborden** [comment]
:thumbsup: when data comes in from the CSVs, what types are they? I'm unclear on when we need to convert to floats, strings, or ints.

**Comment by mikeubell** [comment]
👍

**Comment by tdooner** [comment]
@adborden The data types come from the `csvsql` script, which infers it based on a sample of rows. IMHO it would be better to just use strings for everything for consistency. There is probably an option to do this, but I'll figure that out later.

**Comment by adborden** [comment]
On Tue, 2016-09-20 at 20:09 -0700, Tom Dooner <notifications@github.com> wrote:
> @adborden The data types come from the `csvsql` script, which infers it based on a sample of rows. IMHO it would be better to just use strings for everything for consistency. There is probably an option to do this, but I'll figure that out later.

Sounds good, so if I'm wondering what the type is that I'm working with,
for most cases I can just check the csv?

--
Aaron D Borden
Human and Hacker

**Pull request merged**
