### PR TITLE
Fix totals for largest contributors

### LINKED ISSUE #255: office_title missing in largest_small_proportion in totals.json
In the dummy data for totals.json the objects in the `largest_small_proportion` array had a key `office_title` with the title of the office the candidate was running for. Showing the office title is spec'd in the mockup.

Can we get that key in the real data?

example of data as it is now:
```
"largest_small_proportion": [
      {
        "slug": "esmeralda-cortez-rosales",
        "type": "office",
        "title": "Oakland November 3rd, 2020 General Election",
        "candidate": "Esmeralda Cortez Rosales",
        "proportion": 0.30365816636308446
      },
      {
        "slug": "benjamin-sam-davis",
        "type": "office",
        "title": "Oakland November 3rd, 2020 General Election",
        "candidate": "Benjamin \"Sam\" Davis",
        "proportion": 0.17897458696796412
      },
      {
        "slug": "rebecca-kaplan",
        "type": "office",
        "title": "Oakland November 3rd, 2020 General Election",
        "candidate": "Rebecca Kaplan",
        "proportion": 0.08271537951407729
      }
    ]
```

### PR DESCRIPTION
**Pull request by mikeubell**
Eliminates PACs (recipient committees) from the calculations.
Also fix #255: add office_title.

### CODE REVIEW

**Comment by tdooner** [comment]
<details>
<summary>Build diff from Commit ea03810950d782fb5a11fa5d17077388d667be38:</summary>

```diff
diff --git a/build/_data/elections/oakland/2014-11-04.json b/build/_data/elections/oakland/2014-11-04.json
index 0239d12..2082e89 100644
--- a/build/_data/elections/oakland/2014-11-04.json
+++ b/build/_data/elections/oakland/2014-11-04.json
@@ -2,14 +2,14 @@
   "total_contributions": 2020351.7600000002,
   "total_contributions_by_source": {
     "Out of State": 118791.94,
-    "Within Oakland": 941602.7699999998,
+    "Within Oakland": 941602.77,
     "Within California": 651191.06
   },
   "contributions_by_type": {
     "Committee": 89195.35,
     "Individual": 1345198.4,
     "Unitemized": 122693.37999999999,
-    "Self Funding": 120324.8,
+    "Self Funding": 120324.79999999999,
     "Other (includes Businesses)": 156867.22
   },
   "most_expensive_races": [
@@ -69,7 +69,7 @@
     {
       "name": "Len Raphael",
       "election_name": "oakland-2014",
-      "total_contributions": 31623.690000000002
+      "total_contributions": 31623.69
     },
     {
       "name": "Charles Williams",
@@ -88,7 +88,7 @@
       "name": "Len Raphael",
       "type": "Office",
       "election_name": "oakland-2014",
-      "total_contributions": 31623.690000000002
+      "total_contributions": 31623.69
     },
     {
       "name": "Charles Williams",
@@ -111,7 +111,7 @@
       "name": "Len Raphael",
       "type": "Office",
       "election_name": "oakland-2014",
-      "total_spending": 31623.690000000002
+      "total_spending": 31623.69
     },
     {
       "name": "Charles Williams",
@@ -131,7 +131,7 @@
       "name": "Len Raphael",
       "type": "Office",
       "election_name": "oakland-2014",
-      "total_spending": 31623.690000000002
+      "total_spending": 31623.69
     },
     {
       "name": "Charles Williams",
diff --git a/build/_data/elections/oakland/2016-11-08.json b/build/_data/elections/oakland/2016-11-08.json
index 5670663..5a5b042 100644
--- a/build/_data/elections/oakland/2016-11-08.json
+++ b/build/_data/elections/oakland/2016-11-08.json
@@ -6,7 +6,7 @@
     "Within California": 9350484.879999999
   },
   "contributions_by_type": {
-    "Committee": 9083914.030000001,
+    "Committee": 9083914.03,
     "Individual": 10453339.77,
     "Unitemized": 70132.93,
     "Self Funding": 92561.14,
@@ -29,7 +29,7 @@
       "slug": "infrastructure-and-housing-bonds",
       "type": "referendum",
       "title": "Measure KK",
-      "amount": 450809.57999999996
+      "amount": 450809.58
     }
   ],
   "largest_small_proportion": [
diff --git a/build/_data/elections/oakland/2018-06-05.json b/build/_data/elections/oakland/2018-06-05.json
index 666352f..e12f489 100644
--- a/build/_data/elections/oakland/2018-06-05.json
+++ b/build/_data/elections/oakland/2018-06-05.json
@@ -47,7 +47,7 @@
       "total_contributions": 15000.0
     },
     {
-      "name": "Oakland Athletics Baseball Company",
+      "name": "Service Employees International Union Local 1021 Issues PAC",
       "election_name": "oakland-june-2018",
       "total_contributions": 10000.0
     }
diff --git a/build/_data/elections/oakland/2018-11-06.json b/build/_data/elections/oakland/2018-11-06.json
index 75ecb64..f2edbf5 100644
--- a/build/_data/elections/oakland/2018-11-06.json
+++ b/build/_data/elections/oakland/2018-11-06.json
@@ -9,7 +9,7 @@
     "Committee": 969489.14,
     "Individual": 2739175.5,
     "Unitemized": 158326.48,
-    "Self Funding": 81959.94,
+    "Self Funding": 81959.93999999999,
     "Other (includes Businesses)": 2687273.8200000003
   },
   "most_expensive_races": [
@@ -29,7 +29,7 @@
       "slug": "vacant-property-parcel-tax",
       "type": "referendum",
       "title": "Measure W",
-      "amount": 776996.58
+      "amount": 776996.5800000001
     }
   ],
   "largest_small_proportion": [
@@ -46,7 +46,7 @@
       "type": "office",
       "title": "Oakland November 6th, 2018 Election",
       "candidate": "Cat Brooks",
-      "proportion": 0.3735887090492527,
+      "proportion": 0.3735887090492526,
       "office_title": "Mayor"
     },
     {
@@ -82,7 +82,7 @@
       "name": "Brenda Roberts",
       "type": "Office",
       "election_name": "oakland-2018",
-      "total_contributions": 53757.130000000005
+      "total_contributions": 53757.13
     },
     {
       "name": "Charlie Michelson",
@@ -142,7 +142,7 @@
       "name": "Brenda Roberts",
       "type": "Office",
       "election_name": "oakland-2018",
-      "total_spending": 53757.130000000005
+      "total_spending": 53757.13
     },
     {
       "name": "Charlie Michelson",
diff --git a/build/_data/elections/oakland/2020-11-03.json b/build/_data/elections/oakland/2020-11-03.json
index 5cac87e..5086a67 100644
--- a/build/_data/elections/oakland/2020-11-03.json
+++ b/build/_data/elections/oakland/2020-11-03.json
@@ -3,7 +3,7 @@
   "total_contributions_by_source": {
     "Out of State": 14673.84,
     "Within Oakland": 132496.51,
-    "Within California": 137393.71000000002
+    "Within California": 137393.71
   },
   "contributions_by_type": {
     "Committee": 26723.67,
@@ -72,14 +72,14 @@
       "total_contributions": 4192.47
     },
     {
-      "name": "Ces Butner",
+      "name": "UA Local 342 PAC Fund",
       "election_name": "oakland-2020",
       "total_contributions": 1700.0
     }
   ],
   "top_contributors_for_offices": [
     {
-      "name": "Laborers Local 304 PAC Account Small Contributor Committee",
+      "name": "UA Local 342 PAC Fund",
       "type": "Office",
       "election_name": "oakland-2020",
       "total_contributions": 1700.0
@@ -91,7 +91,7 @@
       "total_contributions": 1700.0
     },
     {
-      "name": "Northern California Carpenters Regional Council SCC",
+      "name": "Sheet Metal Workers' International Association Local Union No. 104 PAC",
       "type": "Office",
       "election_name": "oakland-2020",
       "total_contributions": 1700.0
@@ -131,7 +131,7 @@
       "total_spending": 4192.47
     },
     {
-      "name": "Northern California Carpenters Regional Council SCC",
+      "name": "Sheet Metal Workers' International Association Local Union No. 104 PAC",
       "type": "Office",
       "election_name": "oakland-2020",
       "total_spending": 1700.0
@@ -139,7 +139,7 @@
   ],
   "top_spenders_for_offices": [
     {
-      "name": "Laborers Local 304 PAC Account Small Contributor Committee",
+      "name": "UA Local 342 PAC Fund",
       "type": "Office",
       "election_name": "oakland-2020",
       "total_spending": 1700.0
@@ -151,7 +151,7 @@
       "total_spending": 1700.0
     },
     {
-      "name": "Northern California Carpenters Regional Council SCC",
+      "name": "Sheet Metal Workers' International Association Local Union No. 104 PAC",
       "type": "Office",
       "election_name": "oakland-2020",
       "total_spending": 1700.0
diff --git a/build/_data/referendum_opposing/oakland/2016-11-08/infrastructure-and-housing-bonds.json b/build/_data/referendum_opposing/oakland/2016-11-08/infrastructure-and-housing-bonds.json
index 4ad9b68..dc33b75 100644
--- a/build/_data/referendum_opposing/oakland/2016-11-08/infrastructure-and-housing-bonds.json
+++ b/build/_data/referendum_opposing/oakland/2016-11-08/infrastructure-and-housing-bonds.json
@@ -8,7 +8,7 @@
   "voters_edge_url": null,
   "contributions_by_region": [
     {
-      "amount": 20597.949999999997,
+      "amount": 20597.95,
       "locale": "Within California"
     },
     {
@@ -23,7 +23,7 @@
     },
     {
       "type": "Other (includes Businesses)",
-      "amount": 36372.240000000005
+      "amount": 36372.24
     }
   ],
   "opposing_organizations": [
@@ -34,5 +34,5 @@
       "amount": 86147.98
     }
   ],
-  "total_contributions": 43872.24
+  "total_contributions": 43872.240000000005
 }
diff --git a/build/_data/referendum_opposing/oakland/2018-11-06/vacant-property-parcel-tax.json b/build/_data/referendum_opposing/oakland/2018-11-06/vacant-property-parcel-tax.json
index cc6ec4c..aa0dc95 100644
--- a/build/_data/referendum_opposing/oakland/2018-11-06/vacant-property-parcel-tax.json
+++ b/build/_data/referendum_opposing/oakland/2018-11-06/vacant-property-parcel-tax.json
@@ -12,7 +12,7 @@
       "locale": "Out of State"
     },
     {
-      "amount": 357197.32999999996,
+      "amount": 357197.33,
       "locale": "Within California"
     },
     {
@@ -48,5 +48,5 @@
       "amount": 1483.34
     }
   ],
-  "total_contributions": 776996.58
+  "total_contributions": 776996.5800000001
 }
diff --git a/build/_data/referendum_supporting/oakland/2016-11-08/infrastructure-and-housing-bonds.json b/build/_data/referendum_supporting/oakland/2016-11-08/infrastructure-and-housing-bonds.json
index c42c485..6176110 100644
--- a/build/_data/referendum_supporting/oakland/2016-11-08/infrastructure-and-housing-bonds.json
+++ b/build/_data/referendum_supporting/oakland/2016-11-08/infrastructure-and-housing-bonds.json
@@ -16,7 +16,7 @@
       "locale": "Within California"
     },
     {
-      "amount": 268387.33999999997,
+      "amount": 268387.34,
       "locale": "Within Oakland"
     }
   ],
@@ -42,5 +42,5 @@
       "amount": 413909.6
     }
   ],
-  "total_contributions": 406937.33999999997
+  "total_contributions": 406937.34
 }
diff --git a/build/_data/referendum_supporting/oakland/2016-11-08/just-cause-for-eviction-and-rent-adjustment.json b/build/_data/referendum_supporting/oakland/2016-11-08/just-cause-for-eviction-and-rent-adjustment.json
index 30f4854..08af260 100644
--- a/build/_data/referendum_supporting/oakland/2016-11-08/just-cause-for-eviction-and-rent-adjustment.json
+++ b/build/_data/referendum_supporting/oakland/2016-11-08/just-cause-for-eviction-and-rent-adjustment.json
@@ -23,7 +23,7 @@
   "contributions_by_type": [
     {
       "type": "Committee",
-      "amount": 533317.2400000002
+      "amount": 533317.24
     },
     {
       "type": "Individual",
diff --git a/build/_data/referendum_supporting/oakland/2018-11-06/hotel-employee-minimum-wage-and-workplace-protections.json b/build/_data/referendum_supporting/oakland/2018-11-06/hotel-employee-minimum-wage-and-workplace-protections.json
index 7fdd0d0..a669e46 100644
--- a/build/_data/referendum_supporting/oakland/2018-11-06/hotel-employee-minimum-wage-and-workplace-protections.json
+++ b/build/_data/referendum_supporting/oakland/2018-11-06/hotel-employee-minimum-wage-and-workplace-protections.json
@@ -12,7 +12,7 @@
       "locale": "Out of State"
     },
     {
-      "amount": 163055.91999999998,
+      "amount": 163055.92,
       "locale": "Within California"
     },
     {
@@ -31,7 +31,7 @@
     },
     {
       "type": "Other (includes Businesses)",
-      "amount": 536197.6699999999
+      "amount": 536197.67
     }
   ],
   "supporting_organizations": [
diff --git a/build/_data/referendum_supporting/oakland/2020-03-03/oakland-parks-and-recreation-preservation-litter-reduction-and-homelessness-support-act.json b/build/_data/referendum_supporting/oakland/2020-03-03/oakland-parks-and-recreation-preservation-litter-reduction-and-homelessness-support-act.json
index ef31af9..4575ba4 100644
--- a/build/_data/referendum_supporting/oakland/2020-03-03/oakland-parks-and-recreation-preservation-litter-reduction-and-homelessness-support-act.json
+++ b/build/_data/referendum_supporting/oakland/2020-03-03/oakland-parks-and-recreation-preservation-litter-reduction-and-homelessness-support-act.json
@@ -35,7 +35,7 @@
       "id": "1423153",
       "name": "Yes on Q! Oakland Neighbors for our Parks and People",
       "payee": "Yes on Q! Oakland Neighbors for our Parks and People",
-      "amount": 83437.4
+      "amount": 84262.4
     }
   ],
   "total_contributions": 216028.0
diff --git a/build/_data/stats.json b/build/_data/stats.json
index 6e6c06e..da18784 100644
--- a/build/_data/stats.json
+++ b/build/_data/stats.json
@@ -1,3 +1,3 @@
 {
-  "date_processed": "2020-07-15 00:30:25 -0700"
+  "date_processed": "2020-07-16 00:29:42 -0700"
 }
diff --git a/build/_data/totals.json b/build/_data/totals.json
index fd48228..945cd49 100644
--- a/build/_data/totals.json
+++ b/build/_data/totals.json
@@ -3,14 +3,14 @@
     "total_contributions": 2020351.7600000002,
     "total_contributions_by_source": {
       "Out of State": 118791.94,
-      "Within Oakland": 941602.7699999998,
+      "Within Oakland": 941602.77,
       "Within California": 651191.06
     },
     "contributions_by_type": {
       "Committee": 89195.35,
       "Individual": 1345198.4,
       "Unitemized": 122693.37999999999,
-      "Self Funding": 120324.8,
+      "Self Funding": 120324.79999999999,
       "Other (includes Businesses)": 156867.22
     },
     "most_expensive_races": [
@@ -70,7 +70,7 @@
       {
         "name": "Len Raphael",
         "election_name": "oakland-2014",
-        "total_contributions": 31623.690000000002
+        "total_contributions": 31623.69
       },
       {
         "name": "Charles Williams",
@@ -89,7 +89,7 @@
         "name": "Len Raphael",
         "type": "Office",
         "election_name": "oakland-2014",
-        "total_contributions": 31623.690000000002
+        "total_contributions": 31623.69
       },
       {
         "name": "Charles Williams",
@@ -112,7 +112,7 @@
         "name": "Len Raphael",
         "type": "Office",
         "election_name": "oakland-2014",
-        "total_spending": 31623.690000000002
+        "total_spending": 31623.69
       },
       {
         "name": "Charles Williams",
@@ -132,7 +132,7 @@
         "name": "Len Raphael",
         "type": "Office",
         "election_name": "oakland-2014",
-        "total_spending": 31623.690000000002
+        "total_spending": 31623.69
       },
       {
         "name": "Charles Williams",
@@ -186,7 +186,7 @@
       "Within California": 9350484.879999999
     },
     "contributions_by_type": {
-      "Committee": 9083914.030000001,
+      "Committee": 9083914.03,
       "Individual": 10453339.77,
       "Unitemized": 70132.93,
       "Self Funding": 92561.14,
@@ -209,7 +209,7 @@
         "slug": "infrastructure-and-housing-bonds",
         "type": "referendum",
         "title": "Measure KK",
-        "amount": 450809.57999999996
+        "amount": 450809.58
       }
     ],
     "largest_small_proportion": [
@@ -407,7 +407,7 @@
         "total_contributions": 15000.0
       },
       {
-        "name": "Oakland Athletics Baseball Company",
+        "name": "Service Employees International Union Local 1021 Issues PAC",
         "election_name": "oakland-june-2018",
         "total_contributions": 10000.0
       }
@@ -490,7 +490,7 @@
       "Committee": 969489.14,
       "Individual": 2739175.5,
       "Unitemized": 158326.48,
-      "Self Funding": 81959.94,
+      "Self Funding": 81959.93999999999,
       "Other (includes Businesses)": 2687273.8200000003
     },
     "most_expensive_races": [
@@ -510,7 +510,7 @@
         "slug": "vacant-property-parcel-tax",
         "type": "referendum",
         "title": "Measure W",
-        "amount": 776996.58
+        "amount": 776996.5800000001
       }
     ],
     "largest_small_proportion": [
@@ -527,7 +527,7 @@
         "type": "office",
         "title": "Oakland November 6th, 2018 Election",
         "candidate": "Cat Brooks",
-        "proportion": 0.3735887090492527,
+        "proportion": 0.3735887090492526,
         "office_title": "Mayor"
       },
       {
@@ -563,7 +563,7 @@
         "name": "Brenda Roberts",
         "type": "Office",
         "election_name": "oakland-2018",
-        "total_contributions": 53757.130000000005
+        "total_contributions": 53757.13
       },
       {
         "name": "Charlie Michelson",
@@ -623,7 +623,7 @@
         "name": "Brenda Roberts",
         "type": "Office",
         "election_name": "oakland-2018",
-        "total_spending": 53757.130000000005
+        "total_spending": 53757.13
       },
       {
         "name": "Charlie Michelson",
@@ -664,7 +664,7 @@
     "total_contributions_by_source": {
       "Out of State": 14673.84,
       "Within Oakland": 132496.51,
-      "Within California": 137393.71000000002
+      "Within California": 137393.71
     },
     "contributions_by_type": {
       "Committee": 26723.67,
@@ -733,14 +733,14 @@
         "total_contributions": 4192.47
       },
       {
-        "name": "Ces Butner",
+        "name": "UA Local 342 PAC Fund",
         "election_name": "oakland-2020",
         "total_contributions": 1700.0
       }
     ],
     "top_contributors_for_offices": [
       {
-        "name": "Laborers Local 304 PAC Account Small Contributor Committee",
+        "name": "UA Local 342 PAC Fund",
         "type": "Office",
         "election_name": "oakland-2020",
         "total_contributions": 1700.0
@@ -752,7 +752,7 @@
         "total_contributions": 1700.0
       },
       {
-        "name": "Northern California Carpenters Regional Council SCC",
+        "name": "Sheet Metal Workers' International Association Local Union No. 104 PAC",
         "type": "Office",
         "election_name": "oakland-2020",
         "total_contributions": 1700.0
@@ -792,7 +792,7 @@
         "total_spending": 4192.47
       },
       {
-        "name": "Northern California Carpenters Regional Council SCC",
+        "name": "Sheet Metal Workers' International Association Local Union No. 104 PAC",
         "type": "Office",
         "election_name": "oakland-2020",
         "total_spending": 1700.0
@@ -800,7 +800,7 @@
     ],
     "top_spenders_for_offices": [
       {
-        "name": "Laborers Local 304 PAC Account Small Contributor Committee",
+        "name": "UA Local 342 PAC Fund",
         "type": "Office",
         "election_name": "oakland-2020",
         "total_spending": 1700.0
@@ -812,7 +812,7 @@
         "total_spending": 1700.0
       },
       {
-        "name": "Northern California Carpenters Regional Council SCC",
+        "name": "Sheet Metal Workers' International Association Local Union No. 104 PAC",
         "type": "Office",
         "election_name": "oakland-2020",
         "total_spending": 1700.0
```
</details>

**Comment by tdooner** [comment]
Looks good. I'll merge. In the future you can leave out the changes in the `build` directory since they'll get posted here as a comment.

**Comment by ckingbailey** [comment]
🎉

**Comment by mikeubell** [comment]
Hummm... I usually don’t include them.   I guess I did not do that on the second commit.

**Pull request merged**
