### PR TITLE
Add workflow to verify gdrive connect

### PR DESCRIPTION
**Pull request by ChenglimEar**
This allows us to test pulling files from Google Drive after setting up the secrets and variables.  Uses pydrive2

### CODE REVIEW

**Comment by mikeubell** [comment]
<details>
<summary>Build diff from Commit 5e897629ef374bec962398c296b586364501520c:</summary>

```diff
diff --git a/build/_candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.md b/build/_candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.md
index 0f638d1..209e371 100644
--- a/build/_candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.md
+++ b/build/_candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.md
@@ -4,6 +4,8 @@ committee_name: Sasha Ritzie-Hernandez for Oakland School Board 2023
 filer_id: '1460829'
 is_incumbent: false
 name: Alexandra Ritzie-Hernandez
+occupation: Family Engagement Specialist, Coalition Coordinator, Community Organizer
+photo_url: Alexandra-Ritzie-Hernandez.png
 website_url: https://www.sasharitziehernandez.com/
 facebook_url: https://www.facebook.com/sasha4oakland
 instagram_url: sasha4oakland
diff --git a/build/_candidates/oakland/2023-11-07/christian-miguel-martinez.md b/build/_candidates/oakland/2023-11-07/christian-miguel-martinez.md
index 0f57ba0..2db5160 100644
--- a/build/_candidates/oakland/2023-11-07/christian-miguel-martinez.md
+++ b/build/_candidates/oakland/2023-11-07/christian-miguel-martinez.md
@@ -3,4 +3,6 @@ election: _elections/oakland/2023-11-07.md
 filer_id: ''
 is_incumbent: false
 name: Christian Miguel Martinez
+occupation: Community Innovator and Co-founder of Latitude High School
+photo_url: Christian-Martinez.png
 ---
diff --git a/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md b/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md
index cba14af..63976a1 100644
--- a/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md
+++ b/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md
@@ -3,8 +3,9 @@ election: _elections/oakland/2023-11-07.md
 filer_id: ''
 is_incumbent: false
 name: Jorge C. Lerma
-occupation: Educator, Administrator, Community activist
+occupation: Educator, Administrator, Community Activist
 party_affiliation: Democrat
+photo_url: Jorge-Lerma.jpg
 twitter_url: JorgeforOakland/
 website_url: https://jorgeforoakland.org/
 facebook_url: https://www.facebook.com/JorgeforOakland/
diff --git a/build/_data/candidates/oakland/2018-11-06/courtney-ruby.json b/build/_data/candidates/oakland/2018-11-06/courtney-ruby.json
index d110853..9f8e90b 100644
--- a/build/_data/candidates/oakland/2018-11-06/courtney-ruby.json
+++ b/build/_data/candidates/oakland/2018-11-06/courtney-ruby.json
@@ -1,5 +1,5 @@
 {
-  "id": 63,
+  "id": 62,
   "name": "Courtney Ruby",
   "photo_url": "courtney-ruby.png",
   "website_url": "https://courtneyruby.com/",
diff --git a/build/_data/candidates/oakland/2018-11-06/jesse-a-j-smith.json b/build/_data/candidates/oakland/2018-11-06/jesse-a-j-smith.json
index f5abddd..10a4fb7 100644
--- a/build/_data/candidates/oakland/2018-11-06/jesse-a-j-smith.json
+++ b/build/_data/candidates/oakland/2018-11-06/jesse-a-j-smith.json
@@ -1,5 +1,5 @@
 {
-  "id": 29,
+  "id": 63,
   "name": "Jesse A.J. Smith",
   "photo_url": "Jesse-Smith.png",
   "website_url": "https://oaksmith2018.com/",
diff --git a/build/_data/candidates/oakland/2020-11-03/barbara-parker.json b/build/_data/candidates/oakland/2020-11-03/barbara-parker.json
index 1a9a2dc..9c07ab0 100644
--- a/build/_data/candidates/oakland/2020-11-03/barbara-parker.json
+++ b/build/_data/candidates/oakland/2020-11-03/barbara-parker.json
@@ -1,5 +1,5 @@
 {
-  "id": 57,
+  "id": 56,
   "name": "Barbara Parker",
   "photo_url": "barbara_parker.png",
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2020-11-03/derreck-b-johnson.json b/build/_data/candidates/oakland/2020-11-03/derreck-b-johnson.json
index 822417c..bbd612f 100644
--- a/build/_data/candidates/oakland/2020-11-03/derreck-b-johnson.json
+++ b/build/_data/candidates/oakland/2020-11-03/derreck-b-johnson.json
@@ -1,5 +1,5 @@
 {
-  "id": 59,
+  "id": 58,
   "name": "Derreck B. Johnson",
   "photo_url": "derreck_johnson_sub.jpg",
   "website_url": "https://www.johnsonforoakland.com/",
diff --git a/build/_data/candidates/oakland/2020-11-03/eli-ferran.json b/build/_data/candidates/oakland/2020-11-03/eli-ferran.json
index 80ad235..9bcc75f 100644
--- a/build/_data/candidates/oakland/2020-11-03/eli-ferran.json
+++ b/build/_data/candidates/oakland/2020-11-03/eli-ferran.json
@@ -1,5 +1,5 @@
 {
-  "id": 58,
+  "id": 57,
   "name": "Eli Ferran",
   "photo_url": "Eli_Ferran.jpg",
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2020-11-03/nancy-sidebotham.json b/build/_data/candidates/oakland/2020-11-03/nancy-sidebotham.json
index c35fbbd..47a5508 100644
--- a/build/_data/candidates/oakland/2020-11-03/nancy-sidebotham.json
+++ b/build/_data/candidates/oakland/2020-11-03/nancy-sidebotham.json
@@ -1,5 +1,5 @@
 {
-  "id": 61,
+  "id": 60,
   "name": "Nancy Sidebotham",
   "photo_url": "nancy_sidebotham_sub.jpg",
   "website_url": "http://www.nancysidebotham.com",
diff --git a/build/_data/candidates/oakland/2020-11-03/rebecca-kaplan.json b/build/_data/candidates/oakland/2020-11-03/rebecca-kaplan.json
index 4bad77b..731f335 100644
--- a/build/_data/candidates/oakland/2020-11-03/rebecca-kaplan.json
+++ b/build/_data/candidates/oakland/2020-11-03/rebecca-kaplan.json
@@ -1,5 +1,5 @@
 {
-  "id": 60,
+  "id": 59,
   "name": "Rebecca Kaplan",
   "photo_url": "https://s3-us-west-1.amazonaws.com/odca-candidate-photos/rebecca-kaplan.png",
   "website_url": "http://kaplanforoakland.org/",
diff --git a/build/_data/candidates/oakland/2020-11-03/treva-reid.json b/build/_data/candidates/oakland/2020-11-03/treva-reid.json
index 1413f35..9157e6c 100644
--- a/build/_data/candidates/oakland/2020-11-03/treva-reid.json
+++ b/build/_data/candidates/oakland/2020-11-03/treva-reid.json
@@ -1,5 +1,5 @@
 {
-  "id": 46,
+  "id": 45,
   "name": "Treva Reid",
   "photo_url": "treva_reid_sub.jpg",
   "website_url": "https://www.reidforoakland.com/",
diff --git a/build/_data/candidates/oakland/2020-11-03/tri-ngo.json b/build/_data/candidates/oakland/2020-11-03/tri-ngo.json
index c13a537..3e09cc8 100644
--- a/build/_data/candidates/oakland/2020-11-03/tri-ngo.json
+++ b/build/_data/candidates/oakland/2020-11-03/tri-ngo.json
@@ -1,5 +1,5 @@
 {
-  "id": 62,
+  "id": 61,
   "name": "Tri Ngo",
   "photo_url": null,
   "website_url": "https://www.votetri.com",
diff --git a/build/_data/candidates/oakland/2022-11-08/joel-velasquez.json b/build/_data/candidates/oakland/2022-11-08/joel-velasquez.json
index 330e79a..571e548 100644
--- a/build/_data/candidates/oakland/2022-11-08/joel-velasquez.json
+++ b/build/_data/candidates/oakland/2022-11-08/joel-velasquez.json
@@ -1,5 +1,5 @@
 {
-  "id": 30,
+  "id": 29,
   "name": "Joel Velasquez",
   "photo_url": null,
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/john-mimosa-marks.json b/build/_data/candidates/oakland/2022-11-08/john-mimosa-marks.json
index 77d32d3..42c8043 100644
--- a/build/_data/candidates/oakland/2022-11-08/john-mimosa-marks.json
+++ b/build/_data/candidates/oakland/2022-11-08/john-mimosa-marks.json
@@ -1,5 +1,5 @@
 {
-  "id": 31,
+  "id": 30,
   "name": "John Mimosa Marks",
   "photo_url": null,
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/john-reimann.json b/build/_data/candidates/oakland/2022-11-08/john-reimann.json
index a57c29d..9d9d8cf 100644
--- a/build/_data/candidates/oakland/2022-11-08/john-reimann.json
+++ b/build/_data/candidates/oakland/2022-11-08/john-reimann.json
@@ -1,5 +1,5 @@
 {
-  "id": 32,
+  "id": 31,
   "name": "John Reimann",
   "photo_url": "John-Reimann-sm.png",
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/kenny-session.json b/build/_data/candidates/oakland/2022-11-08/kenny-session.json
index 44df7b5..cd3b50c 100644
--- a/build/_data/candidates/oakland/2022-11-08/kenny-session.json
+++ b/build/_data/candidates/oakland/2022-11-08/kenny-session.json
@@ -1,5 +1,5 @@
 {
-  "id": 33,
+  "id": 32,
   "name": "Kenny Session",
   "photo_url": null,
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/kevin-jenkins.json b/build/_data/candidates/oakland/2022-11-08/kevin-jenkins.json
index 8bd0bd2..f96411a 100644
--- a/build/_data/candidates/oakland/2022-11-08/kevin-jenkins.json
+++ b/build/_data/candidates/oakland/2022-11-08/kevin-jenkins.json
@@ -1,5 +1,5 @@
 {
-  "id": 34,
+  "id": 33,
   "name": "Kevin Jenkins",
   "photo_url": "Kevin-Jenkins-sm.png",
   "website_url": "https://www.jenkinsforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/kyra-mungia.json b/build/_data/candidates/oakland/2022-11-08/kyra-mungia.json
index f7a4b3e..cadcaaf 100644
--- a/build/_data/candidates/oakland/2022-11-08/kyra-mungia.json
+++ b/build/_data/candidates/oakland/2022-11-08/kyra-mungia.json
@@ -1,5 +1,5 @@
 {
-  "id": 35,
+  "id": 34,
   "name": "Kyra Mungia",
   "photo_url": "kyra-mungia.jpeg",
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/loren-manuel-taylor.json b/build/_data/candidates/oakland/2022-11-08/loren-manuel-taylor.json
index 0e69159..dded70a 100644
--- a/build/_data/candidates/oakland/2022-11-08/loren-manuel-taylor.json
+++ b/build/_data/candidates/oakland/2022-11-08/loren-manuel-taylor.json
@@ -1,5 +1,5 @@
 {
-  "id": 36,
+  "id": 35,
   "name": "Loren Manuel Taylor",
   "photo_url": "loren-taylor-2022.jpg",
   "website_url": "https://lorenforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/mart-bradley.json b/build/_data/candidates/oakland/2022-11-08/mart-bradley.json
index 93d0380..89abbef 100644
--- a/build/_data/candidates/oakland/2022-11-08/mart-bradley.json
+++ b/build/_data/candidates/oakland/2022-11-08/mart-bradley.json
@@ -1,5 +1,5 @@
 {
-  "id": 37,
+  "id": 36,
   "name": "Mart Bradley",
   "photo_url": null,
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/max-orozco.json b/build/_data/candidates/oakland/2022-11-08/max-orozco.json
index b1cd4b3..e00b3c6 100644
--- a/build/_data/candidates/oakland/2022-11-08/max-orozco.json
+++ b/build/_data/candidates/oakland/2022-11-08/max-orozco.json
@@ -1,5 +1,5 @@
 {
-  "id": 38,
+  "id": 37,
   "name": "Max Orozco",
   "photo_url": "Max Orozco.jpg",
   "website_url": "https://maxorozcod2.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/mike-hutchinson.json b/build/_data/candidates/oakland/2022-11-08/mike-hutchinson.json
index a42d475..dd71982 100644
--- a/build/_data/candidates/oakland/2022-11-08/mike-hutchinson.json
+++ b/build/_data/candidates/oakland/2022-11-08/mike-hutchinson.json
@@ -1,5 +1,5 @@
 {
-  "id": 39,
+  "id": 38,
   "name": "Mike Hutchinson",
   "photo_url": "mike-hutchinson.png",
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/monesha-carter.json b/build/_data/candidates/oakland/2022-11-08/monesha-carter.json
index 322e4d1..1664330 100644
--- a/build/_data/candidates/oakland/2022-11-08/monesha-carter.json
+++ b/build/_data/candidates/oakland/2022-11-08/monesha-carter.json
@@ -1,5 +1,5 @@
 {
-  "id": 40,
+  "id": 39,
   "name": "Monesha Carter",
   "photo_url": null,
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/nancy-sidebotham.json b/build/_data/candidates/oakland/2022-11-08/nancy-sidebotham.json
index d7db111..cb1b881 100644
--- a/build/_data/candidates/oakland/2022-11-08/nancy-sidebotham.json
+++ b/build/_data/candidates/oakland/2022-11-08/nancy-sidebotham.json
@@ -1,5 +1,5 @@
 {
-  "id": 41,
+  "id": 40,
   "name": "Nancy Sidebotham",
   "photo_url": "nancy_sidebotham_sub.jpg",
   "website_url": "https://nancysidebotham.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/nenna-joiner.json b/build/_data/candidates/oakland/2022-11-08/nenna-joiner.json
index 8c86c00..94c77b0 100644
--- a/build/_data/candidates/oakland/2022-11-08/nenna-joiner.json
+++ b/build/_data/candidates/oakland/2022-11-08/nenna-joiner.json
@@ -1,5 +1,5 @@
 {
-  "id": 42,
+  "id": 41,
   "name": "Nenna Joiner",
   "photo_url": "Nenna-Joiner.png",
   "website_url": "https://www.joinerforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/nick-resnick.json b/build/_data/candidates/oakland/2022-11-08/nick-resnick.json
index 0952c49..108755b 100644
--- a/build/_data/candidates/oakland/2022-11-08/nick-resnick.json
+++ b/build/_data/candidates/oakland/2022-11-08/nick-resnick.json
@@ -1,5 +1,5 @@
 {
-  "id": 43,
+  "id": 42,
   "name": "Nick Resnick",
   "photo_url": "Nick-Resnick-sm.png",
   "website_url": "https://www.nickforoaklandschools.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/nikki-fortunato-bas.json b/build/_data/candidates/oakland/2022-11-08/nikki-fortunato-bas.json
index 1d46bbe..57502c9 100644
--- a/build/_data/candidates/oakland/2022-11-08/nikki-fortunato-bas.json
+++ b/build/_data/candidates/oakland/2022-11-08/nikki-fortunato-bas.json
@@ -1,5 +1,5 @@
 {
-  "id": 44,
+  "id": 43,
   "name": "Nikki Fortunato Bas",
   "photo_url": "Nikki_Fortunato_Bas-2022.jpg",
   "website_url": "http://www.nikki4oakland.com",
diff --git a/build/_data/candidates/oakland/2022-11-08/paulina-gonzalez.json b/build/_data/candidates/oakland/2022-11-08/paulina-gonzalez.json
index 4c7218d..395aa85 100644
--- a/build/_data/candidates/oakland/2022-11-08/paulina-gonzalez.json
+++ b/build/_data/candidates/oakland/2022-11-08/paulina-gonzalez.json
@@ -1,5 +1,5 @@
 {
-  "id": 45,
+  "id": 44,
   "name": "Paulina Gonzalez",
   "photo_url": "paulina-gonzalez.png",
   "website_url": "https://paulinaforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/pecolia-manigo.json b/build/_data/candidates/oakland/2022-11-08/pecolia-manigo.json
index 49e75e6..a3c4611 100644
--- a/build/_data/candidates/oakland/2022-11-08/pecolia-manigo.json
+++ b/build/_data/candidates/oakland/2022-11-08/pecolia-manigo.json
@@ -1,5 +1,5 @@
 {
-  "id": 47,
+  "id": 46,
   "name": "Pecolia Manigo",
   "photo_url": "Pecolia-Manigo.png",
   "website_url": "https://www.pecoliaforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/peter-y-liu.json b/build/_data/candidates/oakland/2022-11-08/peter-y-liu.json
index 8f2b450..c85c617 100644
--- a/build/_data/candidates/oakland/2022-11-08/peter-y-liu.json
+++ b/build/_data/candidates/oakland/2022-11-08/peter-y-liu.json
@@ -1,5 +1,5 @@
 {
-  "id": 48,
+  "id": 47,
   "name": "Peter Y. Liu",
   "photo_url": "Peter-Liu.png",
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/renia-webb.json b/build/_data/candidates/oakland/2022-11-08/renia-webb.json
index 1bc4a62..6b7bf48 100644
--- a/build/_data/candidates/oakland/2022-11-08/renia-webb.json
+++ b/build/_data/candidates/oakland/2022-11-08/renia-webb.json
@@ -1,5 +1,5 @@
 {
-  "id": 49,
+  "id": 48,
   "name": "Renia Webb",
   "photo_url": null,
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2022-11-08/seneca-scott.json b/build/_data/candidates/oakland/2022-11-08/seneca-scott.json
index 56eca55..fd73701 100644
--- a/build/_data/candidates/oakland/2022-11-08/seneca-scott.json
+++ b/build/_data/candidates/oakland/2022-11-08/seneca-scott.json
@@ -1,5 +1,5 @@
 {
-  "id": 50,
+  "id": 49,
   "name": "Seneca Scott",
   "photo_url": "seneca-scott.jpg",
   "website_url": "https://senecaforoaklandmayor2022.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/sheng-thao.json b/build/_data/candidates/oakland/2022-11-08/sheng-thao.json
index eec84f0..c3b62b9 100644
--- a/build/_data/candidates/oakland/2022-11-08/sheng-thao.json
+++ b/build/_data/candidates/oakland/2022-11-08/sheng-thao.json
@@ -1,5 +1,5 @@
 {
-  "id": 51,
+  "id": 50,
   "name": "Sheng Thao",
   "photo_url": "Sheng-Thao-2022.jpg",
   "website_url": "https://www.shengforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/stephen-schear.json b/build/_data/candidates/oakland/2022-11-08/stephen-schear.json
index f3b2c92..42aa536 100644
--- a/build/_data/candidates/oakland/2022-11-08/stephen-schear.json
+++ b/build/_data/candidates/oakland/2022-11-08/stephen-schear.json
@@ -1,5 +1,5 @@
 {
-  "id": 52,
+  "id": 51,
   "name": "Stephen Schear",
   "photo_url": "stephen-schear-sm.png",
   "website_url": "https://stephenschear.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/treva-d-reid.json b/build/_data/candidates/oakland/2022-11-08/treva-d-reid.json
index 7432a17..d3d7b89 100644
--- a/build/_data/candidates/oakland/2022-11-08/treva-d-reid.json
+++ b/build/_data/candidates/oakland/2022-11-08/treva-d-reid.json
@@ -1,5 +1,5 @@
 {
-  "id": 53,
+  "id": 52,
   "name": "Treva D. Reid",
   "photo_url": "treva-reid.png",
   "website_url": "https://www.reidforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/tyron-c-jordan.json b/build/_data/candidates/oakland/2022-11-08/tyron-c-jordan.json
index 0b0ab25..02c91d7 100644
--- a/build/_data/candidates/oakland/2022-11-08/tyron-c-jordan.json
+++ b/build/_data/candidates/oakland/2022-11-08/tyron-c-jordan.json
@@ -1,5 +1,5 @@
 {
-  "id": 54,
+  "id": 53,
   "name": "Tyron C. Jordan",
   "photo_url": "TyronJordan-sm.png",
   "website_url": "https://www.tyronjordanforoakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/valarie-bachelor.json b/build/_data/candidates/oakland/2022-11-08/valarie-bachelor.json
index 3714d10..dac58e8 100644
--- a/build/_data/candidates/oakland/2022-11-08/valarie-bachelor.json
+++ b/build/_data/candidates/oakland/2022-11-08/valarie-bachelor.json
@@ -1,5 +1,5 @@
 {
-  "id": 55,
+  "id": 54,
   "name": "Valarie Bachelor",
   "photo_url": "Valarie Bachelor.jpg",
   "website_url": "https://www.val4oakland.com/",
diff --git a/build/_data/candidates/oakland/2022-11-08/yakpasua-michael-gbagba-zazaboi.json b/build/_data/candidates/oakland/2022-11-08/yakpasua-michael-gbagba-zazaboi.json
index 4a60f5f..14ecd95 100644
--- a/build/_data/candidates/oakland/2022-11-08/yakpasua-michael-gbagba-zazaboi.json
+++ b/build/_data/candidates/oakland/2022-11-08/yakpasua-michael-gbagba-zazaboi.json
@@ -1,5 +1,5 @@
 {
-  "id": 56,
+  "id": 55,
   "name": "Yakpasua Michael Gbagba Zazaboi",
   "photo_url": null,
   "website_url": null,
diff --git a/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json b/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json
index cc16fc8..392b0cb 100644
--- a/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json
+++ b/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json
@@ -1,7 +1,7 @@
 {
   "id": 15,
   "name": "Alexandra Ritzie-Hernandez",
-  "photo_url": null,
+  "photo_url": "Alexandra-Ritzie-Hernandez.png",
   "website_url": "https://www.sasharitziehernandez.com/",
   "twitter_url": null,
   "facebook_url": "https://www.facebook.com/sasha4oakland",
@@ -16,7 +16,7 @@
   "committee_name": "Sasha Ritzie-Hernandez for Oakland School Board 2023",
   "is_accepted_expenditure_ceiling": null,
   "is_incumbent": false,
-  "occupation": null,
+  "occupation": "Family Engagement Specialist, Coalition Coordinator, Community Organizer",
   "party_affiliation": null,
   "is_winner": null,
   "filer_id": 1460829,
diff --git a/build/_data/candidates/oakland/2023-11-07/christian-miguel-martinez.json b/build/_data/candidates/oakland/2023-11-07/christian-miguel-martinez.json
index 63f7a83..38288b6 100644
--- a/build/_data/candidates/oakland/2023-11-07/christian-miguel-martinez.json
+++ b/build/_data/candidates/oakland/2023-11-07/christian-miguel-martinez.json
@@ -1,7 +1,7 @@
 {
   "id": 13,
   "name": "Christian Miguel Martinez",
-  "photo_url": null,
+  "photo_url": "Christian-Martinez.png",
   "website_url": null,
   "twitter_url": null,
   "facebook_url": null,
@@ -16,7 +16,7 @@
   "committee_name": null,
   "is_accepted_expenditure_ceiling": null,
   "is_incumbent": false,
-  "occupation": null,
+  "occupation": "Community Innovator and Co-founder of Latitude High School",
   "party_affiliation": null,
   "is_winner": null,
   "filer_id": null,
diff --git a/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json b/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json
index 68f25a1..c8b3773 100644
--- a/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json
+++ b/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json
@@ -1,7 +1,7 @@
 {
   "id": 14,
   "name": "Jorge C. Lerma",
-  "photo_url": null,
+  "photo_url": "Jorge-Lerma.jpg",
   "website_url": "https://jorgeforoakland.org/",
   "twitter_url": "JorgeforOakland/",
   "facebook_url": "https://www.facebook.com/JorgeforOakland/",
@@ -16,7 +16,7 @@
   "committee_name": null,
   "is_accepted_expenditure_ceiling": null,
   "is_incumbent": false,
-  "occupation": "Educator, Administrator, Community activist",
+  "occupation": "Educator, Administrator, Community Activist",
   "party_affiliation": "Democrat",
   "is_winner": null,
   "filer_id": null,
diff --git a/build/_data/stats.json b/build/_data/stats.json
index 7fa5453..ae7a271 100644
--- a/build/_data/stats.json
+++ b/build/_data/stats.json
@@ -1,3 +1,3 @@
 {
-  "date_processed": "2023-10-04 00:09:18 -0700"
+  "date_processed": "2023-10-05 00:08:38 -0700"
 }
```
</details>

**Comment by mikeubell** [comment]
<details>
<summary>Build diff from Commit 207ca6124fb8ef977a8d68d74882be2208de3e91:</summary>

```diff

```
</details>

**Comment by mikeubell** [comment]
<details>
<summary>Build diff from Commit 237c39270c180a8edaef6986d72f122bede7c956:</summary>

```diff

```
</details>

**Comment by mikeubell** [comment]
<details>
<summary>Build diff from Commit 4b7d4d62f104a0987a7f5a34e9eb965d2982ad7a:</summary>

```diff

```
</details>

**Comment by mikeubell** [comment]
<details>
<summary>Build diff from Commit 3a99814de1f712f2a3bf32e2b73811c71d7376d4:</summary>

```diff
diff --git a/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md b/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md
index eea27a0..0a26a31 100644
--- a/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md
+++ b/build/_candidates/oakland/2023-11-07/jorge-c-lerma.md
@@ -1,7 +1,7 @@
 ---
 election: _elections/oakland/2023-11-07.md
 committee_name: Jorge Lerma for Oakland School Board 2023
-filer_id: ''
+filer_id: '1463520'
 is_incumbent: false
 name: Jorge C. Lerma
 occupation: Educator, Administrator, Community Activist
diff --git a/build/_committees/1463520.md b/build/_committees/1463520.md
new file mode 100644
index 0000000..0ac77f4
--- /dev/null
+++ b/build/_committees/1463520.md
@@ -0,0 +1,7 @@
+---
+filer_id: '1463520'
+name: Jorge Lerma for Oakland School Board 2023
+candidate_controlled_id: ''
+data_warning: 
+title: Jorge Lerma for Oakland School Board 2023
+---
diff --git a/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json b/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json
index 985ccd3..2de5dbb 100644
--- a/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json
+++ b/build/_data/candidates/oakland/2023-11-07/alexandra-ritzie-hernandez.json
@@ -25,10 +25,10 @@
     "total_contributions": 8008.0,
     "total_expenditures": 7006.77,
     "total_loans_received": 0.0,
-    "total_supporting_independent": 13214.33,
+    "total_supporting_independent": 21443.33,
     "support_list": [
       {
-        "Total": 9034.33,
+        "Total": 17263.33,
         "Cand_ID": 1460829,
         "Filer_ID": "1345259",
         "Filer_NamL": "Oakland Education Association Political Action Committee"
diff --git a/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json b/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json
index e769460..8dcd1d7 100644
--- a/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json
+++ b/build/_data/candidates/oakland/2023-11-07/jorge-c-lerma.json
@@ -19,7 +19,7 @@
   "occupation": "Educator, Administrator, Community Activist",
   "party_affiliation": "Democrat",
   "is_winner": null,
-  "filer_id": null,
+  "filer_id": 1463520,
   "supporting_money": {
     "contributions_received": 0.0,
     "total_contributions": 0.0,
diff --git a/build/_data/committees/1463520.json b/build/_data/committees/1463520.json
new file mode 100644
index 0000000..d4486af
--- /dev/null
+++ b/build/_data/committees/1463520.json
@@ -0,0 +1,6 @@
+{
+  "total_contributions": 0,
+  "contributions": [
+
+  ]
+}
diff --git a/build/_data/elections/oakland/2023-11-07.json b/build/_data/elections/oakland/2023-11-07.json
index 13a1e40..07dac00 100644
--- a/build/_data/elections/oakland/2023-11-07.json
+++ b/build/_data/elections/oakland/2023-11-07.json
@@ -30,7 +30,7 @@
     {
       "name": "Oakland Education Association Political Action Committee",
       "election_name": "oakland-2023",
-      "total_spending": 9034.33
+      "total_spending": 17263.33
     },
     {
       "name": "Oakland Rising Committee sponsored by Center for Empowered Politics",
diff --git a/build/_data/stats.json b/build/_data/stats.json
index f75d1f3..924dc80 100644
--- a/build/_data/stats.json
+++ b/build/_data/stats.json
@@ -1,3 +1,3 @@
 {
-  "date_processed": "2023-10-17 00:09:07 -0700"
+  "date_processed": "2023-10-18 00:10:18 -0700"
 }
diff --git a/build/_data/totals.json b/build/_data/totals.json
index c1b9724..4f89e15 100644
--- a/build/_data/totals.json
+++ b/build/_data/totals.json
@@ -1343,7 +1343,7 @@
       {
         "name": "Oakland Education Association Political Action Committee",
         "election_name": "oakland-2023",
-        "total_spending": 9034.33
+        "total_spending": 17263.33
       },
       {
         "name": "Oakland Rising Committee sponsored by Center for Empowered Politics",
```
</details>

**Review by mikeubell — APPROVED** [review]
I am not familiar with workflows.  These changes look reasonable.  When would this workflow be triggered?

**Comment by ChenglimEar** [comment]
@mikeubell The workflow is set to be manually triggered.  You can manually trigger it under the `Actions` tab.

**Pull request merged**
