### PR TITLE
Feature/ind expenditures calc

### PR DESCRIPTION
**Pull request by joshling1919**
Moving https://github.com/caciviclab/disclosure-backend-static/pull/210 to this PR so that it's easier for someone to just pull it down and work off of it (I had originally opened a PR with my own forked repo since I didn't have write access yet).

I basically ended up implementing all of @tdooner's feedback (aka I used all of the code suggestions that he whipped up 😅 ). The suggestions were all really good and make sense to me!

### CODE REVIEW

**Comment by joshling1919** [comment]
@tdooner let's continue the conversation here!

Thanks for pointing me to the `Measures_Expenditures` view! That looks great!

**Comment by joshling1919** [comment]
sorry, accidentally clicked the 'close' button!

**Comment by tdooner** [comment]
<details>
<summary>Build diff from Commit 2c317403752e0f2359acbcfca84a6e2a5bade93a:</summary>

```diff
diff --git a/build/_data/largest_indpendent_expenditures.json b/build/_data/largest_indpendent_expenditures.json
index bc3a8ae..857d1e7 100644
--- a/build/_data/largest_indpendent_expenditures.json
+++ b/build/_data/largest_indpendent_expenditures.json
@@ -1,17 +1,8 @@
 {
-  "sf-2016": null,
+  "berkeley-2018": null,
   "oakland-2016": null,
-  "sf-june-2018": null,
   "oakland-june-2018": null,
-  "sf-2018": [
-    {
-      "Filer_NamL": "SAN FRANCISCO APARTMENT ASSOCIATION POLITICAL ACTION COMMITTEE",
-      "Total_Amount": 10177.0,
-      "election_name": "sf-2018"
-    }
-  ],
   "oakland-2018": null,
-  "berkeley-2018": null,
   "oakland-2020": null,
   "oakland-march-2020": [
     {
@@ -24,5 +15,14 @@
       "Total_Amount": 40641.0,
       "election_name": "oakland-march-2020"
     }
+  ],
+  "sf-2016": null,
+  "sf-june-2018": null,
+  "sf-2018": [
+    {
+      "Filer_NamL": "SAN FRANCISCO APARTMENT ASSOCIATION POLITICAL ACTION COMMITTEE",
+      "Total_Amount": 10177.0,
+      "election_name": "sf-2018"
+    }
   ]
 }
```
</details>

**Comment by tdooner** [comment]
<details>
<summary>Build diff from Commit 2c317403752e0f2359acbcfca84a6e2a5bade93a:</summary>

```diff
diff --git a/build/_data/largest_indpendent_expenditures.json b/build/_data/largest_indpendent_expenditures.json
index bc3a8ae..857d1e7 100644
--- a/build/_data/largest_indpendent_expenditures.json
+++ b/build/_data/largest_indpendent_expenditures.json
@@ -1,17 +1,8 @@
 {
-  "sf-2016": null,
+  "berkeley-2018": null,
   "oakland-2016": null,
-  "sf-june-2018": null,
   "oakland-june-2018": null,
-  "sf-2018": [
-    {
-      "Filer_NamL": "SAN FRANCISCO APARTMENT ASSOCIATION POLITICAL ACTION COMMITTEE",
-      "Total_Amount": 10177.0,
-      "election_name": "sf-2018"
-    }
-  ],
   "oakland-2018": null,
-  "berkeley-2018": null,
   "oakland-2020": null,
   "oakland-march-2020": [
     {
@@ -24,5 +15,14 @@
       "Total_Amount": 40641.0,
       "election_name": "oakland-march-2020"
     }
+  ],
+  "sf-2016": null,
+  "sf-june-2018": null,
+  "sf-2018": [
+    {
+      "Filer_NamL": "SAN FRANCISCO APARTMENT ASSOCIATION POLITICAL ACTION COMMITTEE",
+      "Total_Amount": 10177.0,
+      "election_name": "sf-2018"
+    }
   ]
 }
```
</details>

**Pull request merged**
