### PR TITLE
Import additional candidate info

### PR DESCRIPTION
**Pull request by adborden**
**Please hold off on merging this, waiting on Suzanne to give a final OK on the candidate bios**

- bio
- committee_name
- is_accepted_expenditure_ceiling
- is_incumbent
- occupation
- party_affiliation

### CODE REVIEW

**Comment by tdooner** [comment]
@adborden Status?

**Comment by adborden** [comment]
There's some chatter of having the candidates review the bios. Unclear
if this has to happen before we can start pulling them or just has to
happen before we're on opendisclosure.io

--
Aaron D Borden
Human and Hacker

**Comment by sfdoran** [comment]
I don't think you need to wait - just intending to give them opportunity
for corrections prior to launch - don't let that hold you back.

**Comment by adborden** [comment]
:+1: Great, I just rebased this, but noticed we're pulling in Bruce Quan's photo now. It's not on S3 yet, so I'll push this as soon as that's up.

**Pull request merged**
